### PR TITLE
Create Pet_Default_v5_Dark.theme

### PR DESCRIPTION
**Pull request by petn**

### CODE REVIEW

**Comment by X-Raym** [comment]
@petn 
I think it would be better to have the version expressed in a 1.0, 1.1 form rather than a date with `/`.
https://github.com/cfillion/reapack-index/wiki/Packaging-Documentation#version

You can see this reference.
https://github.com/ReaTeam/Themes/blob/master/Mods/cfillion_Default%20v4.0%20%2B%20width.theme

**Comment by petn** [comment]
O.K., thanks. The theme is inside the zip named 5.25 cause it is on this version atm. Does it make sense to number it like this?

**Comment by X-Raym** [comment]
Just to be sure, Is 5.25 referring to the REAPER version or is it your theme versions ? (version 5, update number 25) ? Version tag is for the second case (version of the package).

**Comment by petn** [comment]
Hi Raymond,
thanks for asking and helping me.
The first version I made was called 5.0. Then there where the Reaper updates including changes in the theme like the master track layout and the preview. I decided to name it inside the zip to the at this time actual Reaper version because I lost overview when naming it constantly 5.0. And I thought if someone doesn't like the changes I've made he can look inside the zip to see which version it is. Especially the changes I made to the dual pan mode and the meters at 5.22. So in my personal WIP the last one I uploaded on 3rd Oct is named 5.25 (modified colormap and minor corrections), and according to this it is named inside the zip.

Does this make sense or is it more confusing than anything else?
Peter

**Comment by X-Raym** [comment]
@petn 
You are welcome 😸 

well, it is a bit unusual to version a package not based on version of something else (REAPER in this case), this may cause problem if you want to push two updates between one single REAPER update cycle (unless you make something like 5.21, 5.25.1, 5.25.2 if needed), but as long as it is coherent and that it works... I guess there is no probem with that...
One downside of not having your own versionning is that your version number will not highlight the importance of your changes,
like 2.0 can meaks a bit changement from 1.0 (total refactoring), it may be only a 5.25 to 2.56 changes if you are based on REAPER version. Same thing, if you make a minor change (1.0 to 1.0.1) it can interpreted as big change if it goes from REAPER v5.25 to 5.50.

**Comment by petn** [comment]
Raymond thanks, this makes sense. To be sure that I understood right: let's say in the theme is just a tiny change from 5.25 to 5.50, but in REAPER a huge feature is added with 5.50. So my numbering would indicate that there is a huge change to the theme too, and that could be confusing.
In this case it is obviously better to stick with the usual form 1.0, cause it's the first version in the ReaPack and details can be viewed in the stash or added to the changelog in line 3.
I'll change that.

**Comment by X-Raym** [comment]
@petn 
exactly, having your own version system seems better,
I think it is good know 👍

**Comment by X-Raym** [comment]
@petn tell us if the sync as expected, you are the first outside contribution 🎉

**Comment by petn** [comment]
@X-Raym 
I learn from the best! 
@X-Raym 
Yes, hurray! Everything is good now, things can be fixed.

**Comment by X-Raym** [comment]
@petn Bravo for this first contribution 👏 

> Everything is good now, things can be fixed.

Is it good, or is there a fix needed ? ^^

**Comment by petn** [comment]
Ah, I ment "can be fixed" in the way of "It is O.K. as it is, can be finished...". I'm german...language problem.
But I tried to sync the ReaPack and all that's downloaded is a 15KB "Default_5_Dark.ReaperThemeZip", Reaper falls back to theme classic 1.x
Opened in notepad it looks like a HTML-file.

**Comment by X-Raym** [comment]
@cfillion I think we need your help from here 😄

**Comment by cfillion** [comment]
Woops, I put the wrong download URL in the template I sent to Pet. It should be http://stash.reaper.fm/26627/Default_5_Dark.ReaperThemeZip (direct download). The current URL is the stash page.

**Comment by petn** [comment]
@cfillion So **you** "fix" it?
Or do I have to edit it?? Probably no, cause YOU are the MASTER! :-)

**Comment by cfillion** [comment]
@petn It's best if you edit it yourself ~from your fork~, so you have the up-to-date version of the file there for future edits. You will need to send another pull request.

**Comment by petn** [comment]
O.K.

**Pull request merged**
