### PR TITLE
Url Screenshots changed

### PR DESCRIPTION
**Pull request by petn**

### CODE REVIEW

**Comment by petn** [comment]
This is telling s.th. about conflicts. "This branch has conflicts that must be resolved" Only those with write access to this repository can merge pull requests.
What am I doing wrong?

**Comment by cfillion** [comment]
Screenshots updated!

For the conflicts, I think I know what happened (you didn't do anything wrong). I need to fix the contributing instructions to avoid this in the future.

**Comment by cfillion** [comment]
[Got it](https://github.com/ReaTeam/Themes#contributing). Next time, use the Edit button in this repo instead of the one in yours. You should see a "Propose file change" button instead of "Commit changes".

**Comment by petn** [comment]
Thanks a lot!

**Pull request closed without merging**
